name: ci-dgraph-fuzz

on:
  pull_request:
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/*.yml"
      - "**/Dockerfile"
      - "**/Makefile"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  fuzz-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run fuzz tests
        run: |
          #!/bin/bash
          # go env settings
          export GOPATH=~/go
          go test -v ./dql -fuzz="Fuzz" -fuzztime="300s" -fuzzminimizetime="120s"
